version: '3.8'

services:
  redis:
    image: redis:8.0
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: redis_patterns
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
